---
version: '3.3'
services:
  postgres:
    platform: linux/amd64
    image: 'postgres:15.2-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - './:/usr/src/app'
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: